Make documentation-po-update use the first argument as the folder to use
Ref: 4590f54f2c09c4111a6fb8985f53bd405cd7157f
Ref: 62da5093f653c42112c955b5d1a96586e7607481

diff --git a/documentation-po-update b/documentation-po-update
--- a/documentation-po-update
+++ b/documentation-po-update
@@ -1,10 +1,17 @@
 #!/bin/sh
 
+# Fail on error or undefined variable
 set -e
+set -u
 
 # Updates phpMyAdmin documentation
 
-WORKDIR=~/localized_docs/
+if [ -z "${1:-}" ] || [ ! -d "${1:-}" ]; then
+    echo "Usage documentation-po-update ~/localized_docs/"
+    exit 1
+fi
+
+WORKDIR="${1}"
 
 if [ ! -d "$WORKDIR" ] ; then
     git clone git@github.com:phpmyadmin/localized_docs.git "$WORKDIR"
@@ -51,6 +58,3 @@ git push
 
 # Unlock Weblate
 wlc unlock
-
-
-
